### ISSUE TITLE
Missing utt xx from input scp:data/dev/mcep_feats.scp, Letter not in LTS tree

### ISSUE THREAD

**Issue by ikhfa** [bpotard/idlak#6] opened 2016-08-10 07:40 UTC
I'm running the tts_dnn_arctic sample with 48K version. Is it normal getting this kind of warning?

**WARNING (paste-feats:main():paste-feats.cc:136) Missing utt slt_arctic_b0339 from input scp:data/train/mcep_feats.scp
...........
WARNING (paste-feats:main():paste-feats.cc:136) Missing utt slt_arctic_b0539 from input scp:data/train/mcep_feats.scp
LOG (paste-feats:main():paste-feats.cc:157) Done 0 utts, errors on 1132
steps/compute_cmvn_stats.sh data/train exp/compute_cmvn/train data/train
Error computing CMVN stats**

steps/make_pitch.sh --pitch-config conf/pitch-48k.conf data/dev exp/make_pitch/dev /tmp/dnn_feats/arctic2
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi.sourceforge.net/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory data/dev
steps/make_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
Succeeded creating Pitch features for dev
steps/compute_cmvn_stats.sh data/dev exp/compute_cmvn_pitch/dev /tmp/dnn_feats/arctic2
Succeeded creating CMVN stats for dev
copy-feats 'scp:awk -v spk=slt '\''($1 == spk){print}'\'' data/dev/cmvn.scp |' ark,t:- 
LOG (copy-feats:main():copy-feats.cc:100) Copied 1 feature matrices.
129.726
using wsizes: 35 18
Retained 100000 utterances per speaker from data-dir data/dev and put it in data/dev_slt, reducing #utt from 60 to 60
steps/make_pitch.sh --pitch-config conf/pitch-48k.conf --frame_length 18 data/dev_slt exp/make_pitch/dev_slt /tmp/dnn_feats/arctic2
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi.sourceforge.net/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory data/dev_slt
steps/make_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
Succeeded creating Pitch features for dev_slt
steps/make_bndap.sh --bndap-config conf/bndap-48k.conf --frame_length 35 data/dev_slt exp/make_bndap/dev_slt /tmp/dnn_feats/arctic2
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi.sourceforge.net/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory data/dev_slt
steps/make_bndap.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
Succeeded creating Bndap features for dev_slt
steps/make_mcep.sh --sample-frequency 48000 --frame_length 18 data/dev_slt exp/make_mcep/dev_slt /tmp/dnn_feats/arctic2
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi.sourceforge.net/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory data/dev_slt
steps/make_mcep.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
run.pl: 4 / 4 failed, log is in exp/make_mcep/dev_slt/make_mcep._.log
cat: data/dev__/mcep_feats.scp: No such file or directory
paste-feats --length-tolerance=1 scp:data/dev/pitch_feats.scp scp:data/dev/mcep_feats.scp scp:data/dev/bndap_feats.scp ark,scp:/tmp/dnn_feats/arctic2/dev_cmp_feats.ark,data/dev/feats.scp 
WARNING (paste-feats:main():paste-feats.cc:136) Missing utt slt_arctic_a0002 from input scp:data/dev/mcep_feats.scp
..........
WARNING (paste-feats:main():paste-feats.cc:136) Missing utt slt_arctic_a0592 from input scp:data/dev/mcep_feats.scp
LOG (paste-feats:main():paste-feats.cc:157) Done 0 utts, errors on 60
steps/compute_cmvn_stats.sh data/dev exp/compute_cmvn/dev data/dev
Error computing CMVN stats
##### Step 2: label creation

idlaktxp --pretty --tpdb=/home/osboxes/Tesis/idlak/egs/tts_dnn_arctic/s1/../../../idlak-data/en/ga/ data/train/text.xml data/train/text_norm.xml 
WARNING (idlaktxp:GetPron():txplts.cc:96) Letter not in LTS tree: '
..............
WARNING (idlaktxp:GetPron():txplts.cc:96) Letter not in LTS tree: '
idlaktxp --pretty --tpdb=/home/osboxes/Tesis/idlak/egs/tts_dnn_arctic/s1/../../../idlak-data/en/ga/ data/dev/text.xml data/dev/text_norm.xml 
WARNING (idlaktxp:GetPron():txplts.cc:96) Letter not in LTS tree: '
idlaktxp --pretty --tpdb=/home/osboxes/Tesis/idlak/egs/tts_dnn_arctic/s1/../../../idlak-data/en/ga/ data/full/text.xml data/full/text_norm.xml 
WARNING (idlaktxp:GetPron():txplts.cc:96) Letter not in LTS tree: '
WARNING (idlaktxp:GetPron():txplts.cc:96) Letter not in LTS tree: '

**Comment by bpotard** [comment] 2016-08-10 09:39
Most of the warnings I see are fine, however:

> run.pl: 4 / 4 failed, log is in exp/make_mcep/dev_slt/make_mcep..log

Means that the mcep extraction failed. I suspect it is because sptk was not correctly build when running make in "tools". Have you build all the tools successfully, i.e. did `make` in the tools/ directory succeed? If it succeeded, you can look at exp/make_mcep/dev_slt/make_mcep.1.log to see what went wrong. In any case, idlak cannot build the voice without mcep features.

**Comment by ikhfa** [comment] 2016-08-10 11:31
I think there's nothing wrong with the 'tools' build. But, I'll check it again. This is the content of the log:

copy-feats --compress=false "ark,s,cs:compute-mcep-feats.sh --frame_length 18 --srate 48000 scp,p:exp/make_mcep/dev_slt/wav_dev_slt.1.scp ark:- |" ark,scp:/tmp/dnn_feats/arctic2/raw_mcep_dev_slt.1.ark,/tmp/dnn_feats/arctic2/raw_mcep_dev_slt.1.scp 

Started at Wed Aug 10 17:41:51 WIB 2016

copy-feats --compress=false 'ark,s,cs:compute-mcep-feats.sh --frame_length 18 --srate 48000 scp,p:exp/make_mcep/dev_slt/wav_dev_slt.1.scp ark:- |' ark,scp:/tmp/dnn_feats/arctic2/raw_mcep_dev_slt.1.ark,/tmp/dnn_feats/arctic2/raw_mcep_dev_slt.1.scp 

/.../idlak/egs/tts_dnn_arctic/s1/../../../src/featbin//compute-mcep-feats.sh: 34: /.../idlak/egs/tts_dnn_arctic/s1/utils//parse_options.sh: Syntax error: Bad for loop variable

WARNING (copy-feats:Close():kaldi-io.cc:446) Pipe compute-mcep-feats.sh --frame_length 18 --srate 48000 scp,p:exp/make_mcep/dev_slt/wav_dev_slt.1.scp ark:- | had nonzero return status 512

LOG (copy-feats:main():copy-feats.cc:100) Copied 0 feature matrices.

Ended (code 256) at Wed Aug 10 17:41:51 WIB 2016, elapsed time 0 seconds

**Comment by bpotard** [comment] 2016-08-10 11:57
Right, I see what the problem is.

In src/featbin/compute-mcep-feats.sh, the shell to use should be bash (`#!/bin/bash`), not sh. It is not a problem on systems where sh is just a symlink to bash, but it is not your case obviously!

I have now fixed it in the repository.

**Comment by bpotard** [comment] 2016-08-11 14:19
Is that now working for you?
You can either manually modify the first line of src/featbin/compute-mcep-feats.sh or you can perform a git pull.

**Comment by ikhfa** [comment] 2016-08-11 18:19
Yes, it is working now (took me almost 7 hours to train the DNN :D). Thank you. No errors reported, except several warnings like this:

> KALDICEX[Thu Aug 11 14:16:51 2016] INFO:Started Logging
> make-fullctx-ali-dnn --max-sil-phone=15 exp-align/quin_ali_full/final.mdl 'ark:gunzip -c exp-align/quin_ali_full/ali.*.gz|' ark,t:data/full/cex.ark ark,t:data/full/ali
> WARNING (make-fullctx-ali-dnn:main():make-fullctx-ali-dnn.cc:239) Merge of alignment and contexts failed for key slt_arctic_a0086 mismatching number of phones contexts:28 alignment:29`

And tons of this:

> copy-feats scp:data/dev/feats.scp ark,t:- 
> LOG (copy-feats:main():copy-feats.cc:100) Copied 60 feature matrices.
> 1 2 3 61 64 25
> x2x : warning: input data is over the range of type 'short'!
> ..........
> x2x : warning: input data is over the range of type 'short'!
> sox WARN dither: dither clipped 3 samples; decrease volume?

And then in **5b. Alice sample synthesis**:

> Traceback (most recent call last):
>  File "/.../idlak/egs/tts_dnn_arctic/s1/../../../idlak-voice-build/utils/idlak_make_lang.py", line 468, in <module>
>     main()
>  File "/.../idlak/egs/tts_dnn_arctic/s1/../../../idlak-voice-build/utils/idlak_make_lang.py", line 463, in main
>     forward_context(logger, args[0], args[1], args[2], opts.root_name)
>  File "/.../idlak/egs/tts_dnn_arctic/s1/../../../idlak-voice-build/utils/idlak_make_lang.py", line 64, in forward_context
>     dom = parse(input_fname)
>  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1918, in parse
>     return expatbuilder.parse(file)
>  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 924, in parse
>     result = builder.parseFile(fp)
>  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 207, in parseFile
>     parser.Parse(buffer, 0)
> xml.parsers.expat.ExpatError: not well-formed (invalid token): line 2561, column 82
> cat: data/eval/cex.ark: No such file or directory
> copy-feats ark:- ark,scp:/tmp/dnn_feats/arctic2/in_durfeats_eval.ark,/tmp/dnn_feats/arctic2/in_durfeats_eval.scp 
> LOG (copy-feats:main():copy-feats.cc:100) Copied 0 feature matrices.
> steps/compute_cmvn_stats.sh lbldurdata/eval lbldurdata/eval lbldurdata/eval
> Error computing CMVN stats
> 
> nnet-forward exp_dnn/tts_dnn_dur_3_delta_quin5/input_final.feature_transform ark:- ark:- 
> LOG (copy-feats:main():copy-feats.cc:100) Copied 0 feature matrices.
> LOG (nnet-forward:main():nnet-forward.cc:219) Done 0 files in 1.58946e-08min, (fps 0)
> LOG (apply-cmvn:main():apply-cmvn.cc:143) Applied cepstral mean and variance normalization to 0 utterances, errors on 0
> LOG (nnet-forward:main():nnet-forward.cc:219) Done 0 files in 0min, (fps -nan)
> WARNING (nnet-forward:Close():kaldi-io.cc:446) Pipe copy-feats scp:lbldurdata/eval/feats.scp ark:- |  nnet-forward exp_dnn/tts_dnn_dur_3_delta_quin5/input_final.feature_transform ark:- ark:- | apply-> cmvn --print-args=false --norm-vars=true exp_dnn/tts_dnn_dur_3_delta_quin5/cmvn_glob.ark ark:- ark:- | had nonzero return status 256
> cat: 'exp_dnn/tts_dnn_dur_3_delta_quin5/tst_forward/cmp/*.cmp': No such file or directory
> Traceback (most recent call last):
>   File "utils/make_fullctx_mlf_dnn.py", line 112, in <module>
>     main()
>   File "utils/make_fullctx_mlf_dnn.py", line 107, in main
>     make_fullctx_mlf_dnn(args[0], args[1], args[2])
>   File "utils/make_fullctx_mlf_dnn.py", line 51, in make_fullctx_mlf_dnn
>     flabs = parse_fullctx(fullctx)
>   File "utils/make_fullctx_mlf_dnn.py", line 28, in parse_fullctx
>     fp = open(fullctxfile, "r")
> IOError: [Errno 2] No such file or directory: 'data/eval/cex.ark'
> copy-feats ark:data/eval/feat.ark ark,scp:/tmp/dnn_feats/arctic2/in_feats_eval.ark,/tmp/dnn_feats/arctic2/in_feats_eval.scp 
> LOG (copy-feats:main():copy-feats.cc:100) Copied 0 feature matrices.
> steps/compute_cmvn_stats.sh lbldata/eval lbldata/eval lbldata/eval
> Error computing CMVN stats

And, lastly:

> nnet-forward exp_dnn/tts_dnn_train_3_deltasc2_quin5/input_final.feature_transform ark:- ark:- 
> LOG (copy-feats:main():copy-feats.cc:100) Copied 0 feature matrices.
> LOG (nnet-forward:main():nnet-forward.cc:219) Done 0 files in 1.58946e-08min, (fps 0)
> LOG (apply-cmvn:main():apply-cmvn.cc:143) Applied cepstral mean and variance normalization to 0 utterances, errors on 0
> LOG (nnet-forward:main():nnet-forward.cc:219) Done 0 files in 0min, (fps -nan)
> WARNING (nnet-forward:Close():kaldi-io.cc:446) Pipe copy-feats scp:lbldata/eval/feats.scp ark:- | nnet-forward exp_dnn/tts_dnn_train_3_deltasc2_quin5/input_final.feature_transform ark:- ark:- | apply-cmvn --print-args=false --norm-vars=true exp_dnn/tts_dnn_train_3_deltasc2_quin5/cmvn_glob.ark ark:- ark:- | had nonzero return status 256
> 1 6 7 183 190 75
> cat: 'exp_dnn/tts_dnn_train_3_deltasc2_quin5/tst_forward/cmp/*.cmp': No such file or directory
> utils/mlsa_synthesis_63_mlpg.sh: line 79: $cmp: ambiguous redirect
> Extracting variances...
> Creating pdfs...
> Running mlpg...
> mcep smoothing
> utils/mlsa_synthesis_63_mlpg.sh: line 123: $mcep: ambiguous redirect
> f0 smoothing
> bndap smoothing
> utils/mlsa_synthesis_63_mlpg.sh: line 127: $bap: ambiguous redirect
> utils/mlsa_synthesis_63_mlpg.sh: line 130: $f0: ambiguous redirect
> utils/mlsa_synthesis_63_mlpg.sh: line 159: $mcep.float: ambiguous redirect
> Usage: excitation.py [options] <f0file> [<bndapfile> [<output>]]
> e.g. python to_wav test.raw 
> 
> excitation.py: error: Too many arguments

**Comment by bpotard** [comment] 2016-08-24 08:35
Ok, there are several issues there:
1. you are using a recent version of g++ that triggered a bug (that we had not noticed) in idlak txplts; this ended up generating some random garbage in the normalised files in rare occasion, which sometimes caused crashes. This has now been fixed in the repository.
2. I think you may have to remove the dnn features folder entirely (`rm -rf /tmp/dnn_feats/`) then rerun the training
3. The synthesis does not run at all as the label file has not been generated correctly (because of the bug in 1.); I think I saw in some other logs that you may need to install numpy anyway for the synthesis to work.

I have now added a more thorough check for all required dependencies in tools/; it now checks for sox, python-numpy, csh, and some other things. You should update your git repository, rebuild things in the tools and src folders, probably regenerate the features, train the DNN, and normally everything should now be working fine.

Sorry about these issues!

**Closed as completed** 2018-02-02 17:28 UTC
